- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      docker_image:
        name: nandish1208/myproject
        tag: "1"
        source: pull

    - name: Deploy Docker Container
      docker_container:
        name: myproject_container
        image: nandish1208/myproject:1
        state: started
        restart_policy: always
        published_ports:
          - "8088:8064"
